global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Private.Windows;
global using Windows.Win32;
global using Windows.Win32.Foundation;
global using Windows.Win32.Graphics.Gdi;
global using Windows.Win32.UI.WindowsAndMessaging;
global using Windows.Win32.UI.HiDpi;
global using Windows.Win32.System.Threading;
global using SR = System.Windows.Forms.Primitives.Resources.SR;
